name: weather_app_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_lifecycle_aware: ^0.0.3
  get_it: ^8.0.3
  injectable: ^2.5.0
  injectable_generator: ^2.6.2

  flutter_hooks: ^0.20.5
  intl: ^0.19.0
  shared_preferences: ^2.3.4
  shimmer: ^3.0.0
  logging: ^1.3.0

  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4

  dio: ^5.7.0
  animated_snack_bar: ^0.4.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.7
  dart_mappable: ^4.3.0
  json_annotation: ^4.9.0
  geolocator: ^13.0.4
  equatable: ^2.0.7
  google_fonts: ^6.2.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  flutter_dotenv: ^5.2.1
  google_maps_flutter: ^2.12.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.14
  json_serializable: ^6.9.0
  dart_mappable_builder: ^4.3.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - .env
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
